trigger:
  - development

pool:
  vmImage: ubuntu-latest

variables:
  nuxtProjectFolder: "nuxt3"
  buildOutputFolder: ".output/public"

jobs:
  - job: Build
    displayName: "Build Nuxt 3 App"
    steps:
      - task: UseNode@1
        inputs:
          versionSpec: "18.x"
          checkLatest: true

      - script: |
          pushd $(nuxtProjectFolder) && npm install && popd
          pushd $(nuxtProjectFolder) && npm run generate && popd

      - task: CopyFiles@2
        inputs:
          sourceFolder: "$(nuxtProjectFolder)/$(buildOutputFolder)"
          contents: "**/*"
          targetFolder: "$(Build.ArtifactStagingDirectory)"
          cleanTargetFolder: true

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.ArtifactStagingDirectory)
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
