<template>
  <nav
    :class="{
      relative: view.atTopOfPage,
      'sticky top-0 opacity-95 fade-in-top ': !view.atTopOfPage,
    }"
    class="bg-white border-b border-[#EDEFEB] flex justify-between py-4 px-[25px] items-center"
  >
    <div class="logo flex gap-x-10 items-center">
      <span class="lg:hidden">
        <NuxtLink :to="`/`">
          <img
            src="/bancro-logo.png"
            alt="Bancro"
            class="w-[130px] h-auto object-contain" /></NuxtLink
      ></span>
    </div>
    <div class="flex gap-x-2 items-center">
      <Notifications />
      <NuxtLink to="/settings/profile">
        <span class="h-10 w-10 rounded-full flex items-center justify-center"
          ><SvgSettings
        /></span>
      </NuxtLink>
      <span class="hidden lg:inline"> <ProfileMenu /></span>
      <button class="lg:hidden outline-none" @click="isOpen = true">
        <AppIcon
          icon="mingcute:menu-fill"
          iconClass="text-3xl text-[#163300]"
        />
      </button>
    </div>
  </nav>

  <ModalSide :isOpen="isOpen" @togglePopup="openModal" v-if="isOpen">
    <template #content>
      <div class="h-full bg-white rounded-lg py-10">
        <AppSideBar />
      </div>
    </template>
  </ModalSide>
</template>
<script setup>
import { logOut } from "~/services/authservices";

const isOpen = ref(false);
function openModal() {
  isOpen.value = !isOpen.value;
}
const { $pwa } = useNuxtApp();
const isSigniningOut = ref(false);
const authStore = useAuthStore();

const notifications = ref([]);
const router = useRouter();
const { currentRoute } = router;

const view = ref({
  atTopOfPage: true,
});
const open = ref(false);
onBeforeMount(() => {
  window.addEventListener("scroll", handleScroll);
});
onMounted(() => {
  if (authStore.isLoggedIn) {
    getNotifications();
    setInterval(() => {
      getNotifications();
    }, 2 * 60 * 1000);
  }
});
const notifyParams = reactive({
  PageNumber: 1,
  PageSize: 30,
  BusinessId: authStore?.businessId,
  UserId: authStore.userId,
  Role: "",
});
const unreadnotifications = computed(() => {
  return notifications?.value?.filter((i) => !i.isViewed)?.length;
});
function getNotifications() {
  // getnotification(notifyParams).then((res) => {
  //   notifications.value = res.data.data;
  // });
}

function handleScroll() {
  // when the user scrolls, check the pageYOffset
  if (window.pageYOffset > 500) {
    // user is scrolled
    if (view.value.atTopOfPage) view.value.atTopOfPage = false;
  } else {
    // user is at top of page
    if (!view.value.atTopOfPage) view.value.atTopOfPage = true;
  }
}

watch(currentRoute, () => {
  open.value = false;
});

provide("getNotifications", getNotifications);
provide("notifications", notifications);
provide("unreadnotifications", unreadnotifications);
provide("open", open);
provide("isOpen", isSigniningOut);
</script>
<style lang="scss">
nav {
  .NuxtLink-active.NuxtLink-exact-active {
    color: #165ef0;
  }
}
/* Add the transition class for slide-down effect */
.fade-in-top {
  -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-11-20 13:54:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
.fade-out-top {
  -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-11-20 13:57:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
}
@keyframes fade-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
}
</style>
